### ISSUE TITLE
Adma.h missing

### ISSUE THREAD

**Issue by sauofeyeron** [lab176344/adma_ros_driver#1]
Hello,

I want to port your UDP driver for the ADMA systems by Genesys to ros2. I can't seem to find the Adma.h file referenced in adma_connect.cpp and adma_parse.cpp. Is it some special header you've been supplied by Genesys?

Best wishes
Sauofeyeron

**Comment by lab176344** [comment]
The Adma.h is not missing. That is the custom msg header, once you compile the package you should be able to access it. In the CMakeList.txt add_message() function will do that

**Comment by sauofeyeron** [comment]
Thank you for the quick response!
