### ISSUE TITLE
Adma Delta Option data packets

### ISSUE THREAD

**Issue by AdriveLivingLab** [lab176344/adma_ros_driver#23]
Hey guys,

as there already have been great additions to the recording of standard ADMA data packets, I have been looking into the recording of data packets from the delta option aswell. I was trying to test the recording of data packets from the ADMA delta option, but I failed to setup the two systems at our workshop and I will need to look into the requirements for getting the delta option to work first. Apparently both systems need a GPS signal and correction data before they even start sending? 

Anyways, from my understanding, the Adma_delta.msg needs these changes:

- Line 1: Add Header header _(same as the standard data packets from recent pull request)_
- Line 7: Replace int32 with int16 Code_version
- Line 47: Add float32 TimeMsec
- Line 48: Change int32 to float32 TimeNsec _(same as standard data packet)_

Did you guys have had the chance to work with the delta option data packets yet or is this untested?
Kind regards
Ludwig Kastner

**Comment by lab176344** [comment]
Hello @AdriveLivingLab, Sorry for the delay in reply. It is untested still. If you can send a pull request with the changes i will check and update the master

**Comment by lab176344** [comment]
Closing the issue
