### ISSUE TITLE
Convert ROS bag to ADMA Raw for Post-processing

### ISSUE THREAD

**Issue by scottharvey-luminar** [lab176344/adma_ros_driver#25]
Hi, I'm trying to run post processing on the output of the ROS bags saved from the driver. Has anybody done this type of conversion? Seeing these are the example input data formats https://genesys-offenburg.de/support/software/adma-pp/data-input/

**Comment by lab176344** [comment]
Hu @scottharvey-luminar , Currently there is only possibility of saving the raw stream in ROS bags. There is no direct option to post process the ROS bag data. 

But this can be implemented easily as the `adma_parse.cpp` is still separate from the ROS specific things a seperate file with a subscriber for the ROS bag messages and calling the adma_parse function should do the work.

If you implement the feature, you can of course create a pull request I will check and merge. Thank you
