### ISSUE TITLE
adma_msgs submodule missing in ros_2 branch

### ISSUE THREAD

**Issue by FranzAlbers** [lab176344/adma_ros_driver#8]
There is no reference to the adma_msgs submodule of the ros_2 branch, probably due to a missing .gitmodules file. 

Neither pulling nor opening the adma_msgs submodule on GitHub is possible.

We reconstructed the adma_msgs submodule from the original ROS messages and could contribute it, but we would prefer to use the original version.

**Comment by lab176344** [comment]
We originally wrote this package for ROS 1, ROS 2 was contributed by one of the contributors. So I did not test it out myself. If you  have corrected the bugs, please feel free to create a pull request, i can merge with the ros_2 branch

**Comment by FranzAlbers** [comment]
Thanks for the reply! 

So far, we can build and run the package, but I think there might be some incorrectly received values. So I would prefer the original version.

@gjonik-fhac, could you please help out and commit the missing submodule?

**Comment by lab176344** [comment]
Closing the issue. Pull request #9
